### ISSUE TITLE
TypeError: decoding str is not supported

### ISSUE THREAD

**Issue by dholdaway** [joshblum/profbit#90]
APIError
Traceback (most recent call last):
  File "/home/vagrant/.local/share/virtualenvs/learning_apis_app-NnD07vdN/lib/python3.6/site-packages/requests/models.py", line 861, in text
    content = str(self.content, encoding, errors='replace')
TypeError: decoding str is not supported

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vagrant/learning_apis_app/learning_apis/routes.py", line 76, in stats_api
    response = get_coinbase_stats(access_token, currency, period)
  File "/home/vagrant/learning_apis_app/learning_apis/coinbase_stats.py", line 311, in get_coinbase_stats
    user, accounts = _get_user_and_accounts(access_token, cache_date)
  File "/home/vagrant/learning_apis_app/learning_apis/coinbase_stats.py", line 301, in _get_user_and_accounts
    accounts = paginate_response(client, 'get_accounts', **{'limit': '100'})
  File "/home/vagrant/learning_apis_app/learning_apis/coinbase_stats.py", line 71, in paginate_response
    coinbase_response = coinbase_func(*args, **kwargs)
  File "/home/vagrant/.local/share/virtualenvs/learning_apis_app-NnD07vdN/lib/python3.6/site-packages/coinbase/wallet/client.py", line 276, in get_accounts
    return self._make_api_object(response, Account)
  File "/home/vagrant/.local/share/virtualenvs/learning_apis_app-NnD07vdN/lib/python3.6/site-packages/coinbase/wallet/client.py", line 179, in _make_api_object
    blob = response.json()
  File "/home/vagrant/.local/share/virtualenvs/learning_apis_app-NnD07vdN/lib/python3.6/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/vagrant/.local/share/virtualenvs/learning_apis_app-NnD07vdN/lib/python3.6/site-packages/requests/models.py", line 869, in text
    content = str(self.content, errors='replace')
TypeError: decoding str is not supported

any ideas on this?

**Comment by joshblum** [comment]
what does`$ pip freeze` output?

**Comment by dholdaway** [comment]
atomicwrites==1.3.0
attrs==19.1.0
backcall==0.1.0
beautifulsoup4==4.7.1
blinker==1.4
certifi==2019.3.9
chardet==3.0.4
Click==7.0
codecov==2.0.15
coinbase==2.1.0
coverage==4.5.3
decorator==4.4.0
defusedxml==0.6.0
django-htmlmin==0.11.0
entrypoints==0.3
flake8==3.7.7
Flask==1.0.3
Flask-Compress==1.4.0
Flask-Login==0.4.1
gevent==1.4.0
greenlet==0.4.15
gunicorn==19.9.0
html5lib==1.0.1
idna==2.8
ipython==7.5.0
ipython-genutils==0.2.0
isort==4.3.20
itsdangerous==1.1.0
jedi==0.13.3
Jinja2==2.10.1
MarkupSafe==1.1.1
mccabe==0.6.1
more-itertools==7.0.0
oauthlib==3.0.1
parso==0.4.0
peewee==2.10.2
pexpect==4.7.0
pickleshare==0.7.5
pipenv==2018.11.26
pluggy==0.11.0
prompt-toolkit==2.0.9
psycopg2-binary==2.8.2
ptyprocess==0.6.0
py==1.8.0
pycodestyle==2.5.0
pycryptodome==3.8.1
pyflakes==2.1.1
Pygments==2.4.0
PyJWT==1.7.1
pytest==4.5.0
pytest-cov==2.7.1
python3-openid==3.1.0
raven==6.10.0
requests==2.22.0
requests-oauthlib==1.2.0
sentry-sdk==0.8.0
six==1.12.0
social-auth-app-flask==1.0.0
social-auth-app-flask-peewee==1.0.0
social-auth-core==3.1.0
social-auth-storage-peewee==1.1.0
soupsieve==1.9.1
traitlets==4.3.2
urllib3==1.25.2
virtualenv==16.6.0
virtualenv-clone==0.5.3
wcwidth==0.1.7
webencodings==0.5.1
Werkzeug==0.15.4

**Comment by joshblum** [comment]
There are some differences from what's in the `Pipfile.lock`, can you install those versions first and see if you still have the issue? https://docs.pipenv.org/en/latest/basics/#pipenv-install

**Comment by dholdaway** [comment]
i removed all the pip install files
ran 
pip install pipenv
then
pipenv install
it moans about psycopg2==2.8.2
so i  pip install psycopg2-binary

**Comment by dholdaway** [comment]
pip freeze

beautifulsoup4==4.7.1
blinker==1.4
certifi==2019.3.9
chardet==3.0.4
Click==7.0
coinbase==2.1.0
defusedxml==0.6.0
django-htmlmin==0.11.0
Flask==1.0.3
Flask-Compress==1.4.0
Flask-Login==0.4.1
gevent==1.4.0
greenlet==0.4.15
gunicorn==19.9.0
html5lib==1.0.1
idna==2.8
itsdangerous==1.1.0
Jinja2==2.10.1
MarkupSafe==1.1.1
oauthlib==3.0.1
peewee==2.10.2
pipenv==2018.11.26
psycopg2-binary==2.8.2
pycryptodome==3.8.1
PyJWT==1.7.1
python3-openid==3.1.0
raven==6.10.0
requests==2.22.0
requests-oauthlib==1.2.0
sentry-sdk==0.8.0
six==1.12.0
social-auth-app-flask==1.0.0
social-auth-app-flask-peewee==1.0.0
social-auth-core==3.1.0
social-auth-storage-peewee==1.1.0
soupsieve==1.9.1
urllib3==1.25.2
virtualenv==16.6.0
virtualenv-clone==0.5.3
webencodings==0.5.1
Werkzeug==0.15.4

**Comment by dholdaway** [comment]
i am running it using 

flask run -h 192.168.33.10 -p 5000

**Comment by joshblum** [comment]
I think something is still off with your environment, specifically:`requests==2.22.0` vs `2.20.1` https://github.com/joshblum/profbit/blob/master/Pipfile.lock#L613-L618 as well as `urllib3==1.25.2` vs  `1.24.1` https://github.com/joshblum/profbit/blob/master/Pipfile.lock#L634-L639

**Comment by dholdaway** [comment]
pipenv install
Pipfile.lock (7d5a9a) out of date, updating to (876c01)…
Locking [dev-packages] dependencies…
✔ Success!
Locking [packages] dependencies…
✔ Success!
Updated Pipfile.lock (7d5a9a)!
Installing dependencies from Pipfile.lock (7d5a9a)…
An error occurred while installing psycopg2==2.8.2 --hash=sha256:00cfecb3f3db6eb76dcc763e71777da56d12b6d61db6a2c6ccbbb0bff5421f8f --hash=sha256:076501fc24ae13b2609ba2303d88d4db79072562f0b8cc87ec1667dedff99dc1 --hash=sha256:4e2b34e4c0ddfeddf770d7df93e269700b080a4d2ec514fec668d71895f56782 --hash=sha256:5cacf21b6f813c239f100ef78a4132056f93a5940219ec25d2ef833cbeb05588 --hash=sha256:61f58e9ecb9e4dc7e30be56b562f8fc10ae3addcfcef51b588eed10a5a66100d --hash=sha256:8954ff6e47247bdd134db602fcadfc21662835bd92ce0760f3842eacfeb6e0f3 --hash=sha256:b6e8c854cdc623028e558a409b06ea2f16d13438335941c7765d0a42b5bedd33 --hash=sha256:baca21c0f7344576346e260454d0007313ccca8c170684707a63946b27a56c8f --hash=sha256:bb1735378770fb95dbe392d29e71405d45c8bdcfa064f916504833a92ab03c55 --hash=sha256:de3d3c46c1ee18f996db42d1eb44cf1565cc9e38fb1dbd9b773ff6b3fa8035d7 --hash=sha256:dee885602bb200bdcb1d30f6da6c7bb207360bc786d0a364fe1540dd14af0bab! Will try again.

**Comment by dholdaway** [comment]
I think my pipenv is updating the Pipefile.lock. 

I cut and pasted 

 https://github.com/joshblum/profbit/blob/master/Pipfile.lock#L634-L639

but it looks like its installing  urllib3==1.25.3

**Comment by joshblum** [comment]
Can you checkout the original `Pipfile.lock` without any modifications and try `pipenv install --ignore-pipfile` `--ignore-pipfile — Ignore the Pipfile and install from the Pipfile.lock.`

**Comment by dholdaway** [comment]
yes! that was the issue.

i also think it was to do with a npm issue also.

i have it up and running now.
